name: CDNW CI

on:
  push:
    branches: [dev1, feat/* ]


  pull_request:
    branches:
      - dev1

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: checkout # github action에 보이는 이름
        uses: actions/checkout@v4 # action의 checkout을 v4버전으로 실행한다.

      - name: java setup
        uses: actions/setup-java@v2 # action에서 java환경을 setup한다.
        with:
          distribution: 'temurin' # AdoptOpenJDK를 명시한다. 이외에 corretto, oracle 등이 있다.
          java-version: '17' # java 버전

      - name: make executable gradlew
        run: chmod +x ./gradlew # chmod를 리눅스에서 동작 시켜서 ./gradlew 파일의 권한을 읽을수 있도록 한다.

      - name: Build with Gradle
        run: ./gradlew build -x test # build 후 테스트 수행하게 된다. -x test 를 사용해서 테스트는 진행하지 않도록 설정

      - name: Build Spring Boot Jar
        run: ./gradlew bootJar # 실행 가능한 jar 파일을 만든다.

      - name: Build Docker image # jar 파일을 복사에서 Dockerfile에 넣는다.
        run : docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/test1:1.1 .

      - name: Login to DockerHub # docker hub에 로그인 한다. github에 저장된 DOCKERHUB_USERNAME, DOCKERHUB_TOKEN 사용
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/test1:1.1 # docker에 image push

      # script로 docker 로그인 -> image pull -> 컨테이너 실행(배포)

  deploy-to-ec2:


    needs: build-and-push-docker
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: janghwal/ClothsDaNaWaTEST@feat/test
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            CONTAINER_ID=$(sudo docker ps -q --filter "publish=80-8080")

            if [ ! -z "$CONTAINER_ID" ]; then
              sudo docker stop $CONTAINER_ID
              sudo docker rm $CONTAINER_ID
            fi
 
 
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/test1:1.1
            sudo docker run --env-file ./config/.env --name test1-app -d -p 80:8080 -e TZ=Asia/Seoul ${{ secrets.DOCKERHUB_USERNAME }}/test1:1.1



